public class main_perpustakaan {
    public static void main(String[] args) {
        perpustakaan teknologi1 = new perpustakaan();
        teknologi1.setJudulBuku("Introduction to Java Programming, Comprehensive Version, 10th Edition");
        teknologi1.setKategoriBuku("Teknologi");
        teknologi1.setPenulisBuku(new String[]{"Y. Daniel Liang"});
        teknologi1.setTahunTerbitBuku(2015);
        perpustakaan teknologi2 = new perpustakaan();
        teknologi2.setJudulBuku("Java How to Program, Tenth Edition, Late Objects Version");
        teknologi2.setKategoriBuku("Teknologi");
        teknologi2.setPenulisBuku(new String[]{"Paul Deitel", "Harvey Deitel"});
        teknologi2.setTahunTerbitBuku(2014);
        perpustakaan teknologi3 = new perpustakaan();
        teknologi3.setJudulBuku("Operating System Concepts, Tenth Edition");
        teknologi3.setKategoriBuku("Teknologi");
        teknologi3.setPenulisBuku(new String[]{"Abraham Silberschatz","Peter Baer Galvin", "Greg Gagne"});
        teknologi3.setTahunTerbitBuku(2018);
        perpustakaan teknologi4 = new perpustakaan();
        teknologi4.setJudulBuku("Operating System: Internals and Design Principles, Ninth Edition");
        teknologi4.setKategoriBuku("Teknologi");
        teknologi4.setPenulisBuku(new String[]{"William Stallings"});
        teknologi4.setTahunTerbitBuku(2018);
        perpustakaan teknologi5 = new perpustakaan();
        teknologi5.setJudulBuku("Fundamentals of Information Systems, Eight Edition");
        teknologi5.setKategoriBuku("Teknologi");
        teknologi5.setPenulisBuku(new String[]{"Ralph M. Stair","George W. Reynolds"});
        teknologi5.setTahunTerbitBuku(2017);

        perpustakaan filsafat1 = new perpustakaan();
        filsafat1.setJudulBuku("Filosofi Teras");
        filsafat1.setKategoriBuku("Filsafat");
        filsafat1.setPenulisBuku(new String[]{""});
        filsafat1.setTahunTerbitBuku();
        perpustakaan filsafat2 = new perpustakaan();
        filsafat2.setJudulBuku("");
        filsafat2.setKategoriBuku("Filsafat");
        filsafat2.setPenulisBuku(new String[]{""});
        filsafat2.setTahunTerbitBuku();
        perpustakaan filsafat3 = new perpustakaan();
        filsafat3.setJudulBuku("");
        filsafat3.setKategoriBuku("Filsafat");
        filsafat3.setPenulisBuku(new String[]{""});
        filsafat3.setTahunTerbitBuku();
        perpustakaan filsafat4 = new perpustakaan();
        filsafat4.setJudulBuku("");
        filsafat4.setKategoriBuku("Filsafat");
        filsafat4.setPenulisBuku(new String[]{""});
        filsafat4.setTahunTerbitBuku();
        perpustakaan filsafat5 = new perpustakaan();
        filsafat5.setJudulBuku("");
        filsafat5.setKategoriBuku("Filsafat");
        filsafat5.setPenulisBuku(new String[]{""});
        filsafat5.setTahunTerbitBuku();
        
        perpustakaan sejarah1 = new perpustakaan();
        sejarah1.setJudulBuku("");
        sejarah1.setKategoriBuku("Sejarah");
        sejarah1.setPenulisBuku(new String[]{""});
        sejarah1.setTahunTerbitBuku();
        perpustakaan sejarah2 = new perpustakaan();
        sejarah2.setJudulBuku("");
        sejarah2.setKategoriBuku("Sejarah");
        sejarah2.setPenulisBuku(new String[]{""});
        sejarah2.setTahunTerbitBuku();
        perpustakaan sejarah3 = new perpustakaan();
        sejarah3.setJudulBuku("");
        sejarah3.setKategoriBuku("Sejarah");
        sejarah3.setPenulisBuku(new String[]{""});
        sejarah3.setTahunTerbitBuku();
        perpustakaan sejarah4 = new perpustakaan();
        sejarah4.setJudulBuku("");
        sejarah4.setKategoriBuku("Sejarah");
        sejarah4.setPenulisBuku(new String[]{""});
        sejarah4.setTahunTerbitBuku();
        perpustakaan sejarah5 = new perpustakaan();
        sejarah5.setJudulBuku("");
        sejarah5.setKategoriBuku("Sejarah");
        sejarah5.setPenulisBuku(new String[]{""});
        sejarah5.setTahunTerbitBuku();

        perpustakaan agama1 = new perpustakaan();
        agama1.setJudulBuku("");
        agama1.setKategoriBuku("Agama");
        agama1.setPenulisBuku(new String[]{""});
        agama1.setTahunTerbitBuku();
        perpustakaan agama2 = new perpustakaan();
        agama2.setJudulBuku("");
        agama2.setKategoriBuku("Agama");
        agama2.setPenulisBuku(new String[]{""});
        agama2.setTahunTerbitBuku();
        perpustakaan agama3 = new perpustakaan();
        agama2.setJudulBuku("");
        agama2.setKategoriBuku("Agama");
        agama2.setPenulisBuku(new String[]{""});
        agama2.setTahunTerbitBuku();
        perpustakaan agama4 = new perpustakaan();
        agama4.setJudulBuku("");
        agama4.setKategoriBuku("Agama");
        agama4.setPenulisBuku(new String[]{""});
        agama4.setTahunTerbitBuku();
        perpustakaan agama5 = new perpustakaan();
        agama5.setJudulBuku("");
        agama5.setKategoriBuku("Agama");
        agama5.setPenulisBuku(new String[]{""});
        agama5.setTahunTerbitBuku();

        perpustakaan psikologi1 = new perpustakaan();
        psikologi1.setJudulBuku("");
        psikologi1.setKategoriBuku("Psikologi");
        psikologi1.setPenulisBuku(new String[]{""});
        psikologi1.setTahunTerbitBuku();
        perpustakaan psikologi2 = new perpustakaan();
        psikologi2.setJudulBuku("");
        psikologi2.setKategoriBuku("Psikologi");
        psikologi2.setPenulisBuku(new String[]{""});
        psikologi2.setTahunTerbitBuku();
        perpustakaan psikologi3 = new perpustakaan();
        psikologi3.setJudulBuku("");
        psikologi3.setKategoriBuku("Psikologi");
        psikologi3.setPenulisBuku(new String[]{""});
        psikologi3.setTahunTerbitBuku();
        perpustakaan psikologi4 = new perpustakaan();
        psikologi4.setJudulBuku("");
        psikologi4.setKategoriBuku("Psikologi");
        psikologi4.setPenulisBuku(new String[]{""});
        psikologi4.setTahunTerbitBuku();
        perpustakaan psikologi5 = new perpustakaan();
        psikologi5.setJudulBuku("");
        psikologi5.setKategoriBuku("Psikologi");
        psikologi5.setPenulisBuku(new String[]{""});
        psikologi5.setTahunTerbitBuku();

        perpustakaan politik1 = new perpustakaan();
        politik1.setJudulBuku("");
        politik1.setKategoriBuku("Psikologi");
        politik1.setPenulisBuku(new String[]{""});
        politik1.setTahunTerbitBuku();
        perpustakaan politik2 = new perpustakaan();
        politik2.setJudulBuku("");
        politik2.setKategoriBuku("Psikologi");
        politik2.setPenulisBuku(new String[]{""});
        politik2.setTahunTerbitBuku();
        perpustakaan politik3 = new perpustakaan();
        politik3.setJudulBuku("");
        politik3.setKategoriBuku("Psikologi");
        politik3.setPenulisBuku(new String[]{""});
        politik3.setTahunTerbitBuku();
        perpustakaan politik4 = new perpustakaan();
        politik4.setJudulBuku("");
        politik4.setKategoriBuku("Psikologi");
        politik4.setPenulisBuku(new String[]{""});
        politik4.setTahunTerbitBuku();
        perpustakaan politik5 = new perpustakaan();
        politik5.setJudulBuku("");
        politik5.setKategoriBuku("Psikologi");
        politik5.setPenulisBuku(new String[]{""});
        politik5.setTahunTerbitBuku();

        perpustakaan fiksi1 = new perpustakaan();
        fiksi1.setJudulBuku("");
        fiksi1.setKategoriBuku("Psikologi");
        fiksi1.setPenulisBuku(new String[]{""});
        fiksi1.setTahunTerbitBuku();
        perpustakaan fiksi2 = new perpustakaan();
        fiksi2.setJudulBuku("");
        fiksi2.setKategoriBuku("Psikologi");
        fiksi2.setPenulisBuku(new String[]{""});
        fiksi2.setTahunTerbitBuku();
        perpustakaan fiksi3 = new perpustakaan();
        fiksi3.setJudulBuku("");
        fiksi3.setKategoriBuku("Psikologi");
        fiksi3.setPenulisBuku(new String[]{""});
        fiksi3.setTahunTerbitBuku();
        perpustakaan fiksi4 = new perpustakaan();
        fiksi4.setJudulBuku("");
        fiksi4.setKategoriBuku("Psikologi");
        fiksi4.setPenulisBuku(new String[]{""});
        fiksi4.setTahunTerbitBuku();
        perpustakaan fiksi5 = new perpustakaan();
        fiksi5.setJudulBuku("");
        fiksi5.setKategoriBuku("Psikologi");
        fiksi5.setPenulisBuku(new String[]{""});
        fiksi5.setTahunTerbitBuku();

        perpustakaan perpustakaan = new perpustakaan();
        perpustakaan.setNamaPerpustakaan("Universitas X");
        perpustakaan.awalan();

        teknologi1.menampilkanKategori();
        teknologi1.dataBuku();
        teknologi2.dataBuku();
        teknologi3.dataBuku();
        teknologi4.dataBuku();
        teknologi5.dataBuku();
        filsafat1.menampilkanKategori();
        filsafat1.dataBuku();
        filsafat2.dataBuku();
        filsafat3.dataBuku();
        filsafat4.dataBuku();
        filsafat5.dataBuku();
        sejarah1.menampilkanKategori();
        sejarah1.dataBuku();
        sejarah2.dataBuku();
        sejarah3.dataBuku();
        sejarah4.dataBuku();
        sejarah5.dataBuku();
        agama1.menampilkanKategori();
        agama1.dataBuku();
        agama2.dataBuku();
        agama3.dataBuku();
        agama4.dataBuku();
        agama5.dataBuku();
        psikologi1.menampilkanKategori();
        psikologi1.dataBuku();
        psikologi2.dataBuku();
        psikologi3.dataBuku();
        psikologi4.dataBuku();
        psikologi5.dataBuku();
        politik1.menampilkanKategori();
        politik1.dataBuku();
        politik2.dataBuku();
        politik3.dataBuku();
        politik4.dataBuku();
        politik5.dataBuku();
        fiksi1.menampilkanKategori();
        fiksi1.dataBuku();
        fiksi2.dataBuku();
        fiksi3.dataBuku();
        fiksi4.dataBuku();
        fiksi5.dataBuku();
    }
}
